
name: DriveUp

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
        - "upfiles.sh"

env:
    SSH_ACTIONS: false
    DOWNLOAD_ARIA2: true
    DOWNLOAD: true
    UPLOAD_COW: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install Rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash
      - name: Set Rclone
        run: |
          echo "${{ secrets.RCLONE_CONF }}" > rclone.conf
          mkdir -p /home/runner/.config/rclone/
          chmod 777 /home/runner/.config/rclone/
          mv $GITHUB_WORKSPACE/rclone.conf /home/runner/.config/rclone/
          mkdir -p $GITHUB_WORKSPACE/download
      - name: Install Aria2
        if: env.DOWNLOAD_ARIA2 == 'true'
        run: |
          sudo chmod 777 aria2.sh
          sudo ./aria2.sh
          sudo sed -i 's?dir=/root/downloads?dir=/home/runner/work/DrivesDown/DrivesDown/download?g' /root/.aria2c/aria2.conf
          sudo sed -i 's/max-overall-upload-limit=2M/max-overall-upload-limit=10M/g' /root/.aria2c/aria2.conf
          sudo sed -i 's/seed-time=0/seed-time=1/g' /root/.aria2c/aria2.conf
          sudo sed -i 's/seed-ratio=1.0/#seed-ratio=1.0/g' /root/.aria2c/aria2.conf
          sudo cp -rf /root/.aria2c/ $HOME/.aria2c/
          sudo chattr -i $HOME/.aria2c/*
          sudo chmod 777 $HOME/.aria2c/*
          sudo service aria2 restart
      - name: Install Other
        run: |
          curl -sL https://git.io/cowtransfer | sh 
          sudo mv cowtransfer-uploader /usr/bin/
      - name: View Space
        run: |
          sudo rm -rf /opt/
          df -h $GITHUB_WORKSPACE/download
      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: env.SSH_ACTIONS == 'true'
        with:
          mode: ngrok
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_REGION: ap
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      - name: Download files
        if: env.DOWNLOAD == 'true'
        run: |
          cp upfiles.sh download/
          cd download/
          chmod 777 upfiles.sh
          ./upfiles.sh
      - name: Upload Drives
        run: |
          rclone move -P --exclude "*.{sh,torrent,aria2}" /home/runner/work/DrivesDown/DrivesDown/download/ nice:/
      - name: Upload Files to cowtransfer
        if: env.UPLOAD_COW == 'true'
        run: |
          curl -fsSL git.io/file-transfer | sh
          ./transfer cow --block 2621440 -s -p 64 --no-progress $GITHUB_WORKSPACE/download 2>&1 | tee cowtransfer.log
           echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
           echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v1.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 1
          keep_minimum_runs: 1
